# Generated by Django 4.1.3 on 2022-12-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
