# Generated by Django 4.1.3 on 2022-12-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_shippingaddress_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="name",),
    ]
