# Generated by Django 4.1.3 on 2022-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
