# Generated by Django 4.1.3 on 2022-12-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0007_alter_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                default="AnonymousUser",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                blank=True, default="anonymous", max_length=200, null=True
            ),
        ),
    ]
