# Generated by Django 4.1.3 on 2022-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_customer_customer_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
    ]
